version: '3.7'
services:
  pastec:
    build:
      context: .
      dockerfile: Dockerfile
    image: swissartresearx/pastec:latest
    ports:
      - '4212:4212'
    restart: always
    volumes:
      - ./pastec-index:/pastec/build/pastec-index:rw
    command:
      - /bin/sh 
      - -c
      - |
        ./pastec -p 4212 /pastec/data/visualWordsORB.dat
